### ISSUE TITLE
Reliance on libxmljs leads to compilation error for node v12.0.0 and higher 

### ISSUE THREAD

**Issue by Jakub-L** [znerol/node-xmlshim#12]
See issue: libxmljs/libxmljs/issues/546

I do not think a patch is coming anytime soon - the issue's been hanging since late April and hasn't even been acknowledged by the creator.

Suggestion would be to switch to dependency on [libxmljs2](https://www.npmjs.com/package/libxmljs2)

**Comment by znerol** [comment]
Thanks for opening this issue. This dependency has been a headache since the very beginning of the project. We might be better off by just replacing it with either a pure JavaScript XML parser/serializer or something compiled to webasm or stick to `libxml` but directly call it using [ffi](https://github.com/node-ffi/node-ffi).

**Comment by znerol** [comment]
From [Rust webasm tutorial](https://rustwasm.github.io/docs/book/game-of-life/implementing.html#interfacing-rust-and-javascript):

> When designing an interface between WebAssembly and JavaScript, we want to optimize for the following properties:
> 1. **Minimizing copying into and out of the WebAssembly linear memory.** Unnecessary copies impose unnecessary overhead.
> 2. **Minimizing serializing and deserializing.** Similar to copies, serializing and deserializing also imposes overhead, and often imposes copying as well. If we can pass opaque handles to a data structure — instead of serializing it on one side, copying it into some known location in the WebAssembly linear memory, and deserializing on the other side — we can often reduce a lot of overhead. wasm_bindgen helps us define and work with opaque handles to JavaScript Objects or boxed Rust structures.

Thus, implementing an XML parser/serializer in any language which compiles to webasm does not seem to be a good idea. Copying data from the input stream (node) to the linear webasm memory only to apply some parsing, then calling a JavaScript function which copies that stuff back on the JS engines heap will not perform any better than a pure JS implementation.

This is what we need: [StAX Streaming API for XML](https://en.wikipedia.org/wiki/StAX)

Some JS project which potentially fulfill this:
* [sax-js](https://www.npmjs.com/package/sax) parser, very popular
* [Saxophone](https://www.npmjs.com/package/saxophone) parser, fast
* [XMLWriter for NodeJS](https://www.npmjs.com/package/xml-writer) writer, kinda popular
* [Blog: A story of streaming RDF parsers](https://www.rubensworks.net/blog/2019/03/13/streaming-rdf-parsers/)

**Comment by znerol** [comment]
Updated libxmljs fork and published xmlshim version 0.2.6. This is now compatible with node 12.
