### ISSUE TITLE
No longer builds with recent node versions

### ISSUE THREAD

**Issue by remko** [znerol/node-xmlshim#5]
`npm install xmlshim` no longer works, because the `libxmljs` dependency no longer builds under recent node versions.

Node v4.3.0, npm v2.14.12.

**Comment by znerol** [comment]
I updated libxmljs. Problem is that the newest jsdom which is compatible with xmlshim (0.11.x) does not seem to compile with node 0.11 or newer. I'm not yet sure what is necessary to upgrade to a more recent version of jsdom.

**Comment by znerol** [comment]
This is fixed now. Note though that recent jsdom versions lack support for CDATA.
